CONFIG = {}

CONFIG.REFRESH_RATE = 150       -- ms entre atualizações (mais alto = mais performático, menos fluido)
CONFIG.USE_MPH = false          -- false = KMH | true = MPH

-- Deve ser consistente com USE_MPH
CONFIG.SPEED_MEASURE_UNIT    = "KMH"   -- "KMH" ou "MPH"
CONFIG.DISTANCE_MEASURE_UNIT = "M"     -- "M" ou "FT"

CONFIG.RANGE = 55               -- alcance do raio de detecção (metros)

    -- ── LIMITES DE VELOCIDADE POR TIPO DE VIA ─────────────────────────────────────
CONFIG.SPEED_LIMITS = {
    -- Prefixos reconhecidos (lowercase, verificado com string.find)
    { prefix = "br%-",  limit = 120 },   -- BR-116, BR-101...
    { prefix = "rod%.", limit = 120 },   -- Rod. Fernão Dias...
    { prefix = "rodov", limit = 120 },   -- Rodovia ...
    { prefix = "marg",  limit = 100 },   -- Marginal ...
    { prefix = "av%.",  limit = 100 },   -- Av. Paulista...
    { prefix = "aven",  limit = 100 },   -- Avenida ...
    { prefix = "alam",  limit =  80 },   -- Alameda ...
    { prefix = "rua",   limit =  80 },   -- Rua ...
    { prefix = "r%.",   limit =  80 },   -- R. ...
    { prefix = "via",   limit = 100 },   -- Via Anhanguera...
}

CONFIG.SPEED_LIMITS_DEFAULT = 80        -- fallback para vias não identificadas